version: '3.7'

services:
  mysql-app:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: t3mp0r4l#*
      MYSQL_DATABASE: monkeysapp
    ports:
      - "3306:3306"
    networks:
      - backend
      
  webapp:
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

  sailsjs:
    container_name: "sailsjs"
    tty: true
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.9.3
    restart: always
    container_name: "elasticsearch"
    tty: true
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
    networks:
      - backend

volumes:
  mysql-data:
  esdata:

networks:
  backend:
    driver: bridge
