version: '3.7'

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami-monkeys.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  webapp:
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`monkeys.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  sailsjs:
    container_name: "sailsjs"
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/usr/src/app
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`backend-monkeys.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  mysql:
    container_name: "mysql"
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mkcloud-sails
      MYSQL_USER: sails
      MYSQL_PASSWORD: sailsPowdj940
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.9.3
    restart: always
    container_name: "elasticsearch"
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend

  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer-monkeys.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=traefik"

volumes:
  mysql-data:
  esdata:

networks:
  backend:
    driver: bridge
